In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import scipy


In [7]:
## B-spline class

class Bspline():
    
    def __init__(self, order, knots):
        
        self.knots = knots
        self.order = order
        self.degree = order - 1
        self.num_params = len(knots) + order
        
    def bspline_basis(self, x, k, i, t):
        """
        B-spline basis function value B(j,n) at x.
        
        Input arguments:
         x:
            value where the basis function is to be evaluated
         n:
            B-spline order (2 for linear, 1 for quadratic, etc.)
         i:
            interval index, 0 =< j < numel(t)-k-1

         t:
            knot vector

         Output arguments:
         y:
        
        """
        if k == 0:

            return 1.0 if t[i] <= x < t[i+1] else 0.0

        if t[i+k] == t[i]:

            c1 = 0.0 #indeterminate forms 0/0 are deemed to be zero

        else:
            
            c1 = (x - t[i])/(t[i+k] - t[i]) * self.bspline_basis(x, k-1, i, t)

        if t[i+k+1] == t[i+1]:

            c2 = 0.0 #indeterminate forms 0/0 are deemed to be zero

        else:

            c2 = (t[i+k+1] - x)/(t[i+k+1] - t[i+1]) * self.bspline_basis(x, k-1, i+1, t)
        
        return c1 + c2
    
    def basis_matrix(self, x):
        """
        B-spline basis function value matrix B(n) for x.
        
        Input arguments:
         n:
            B-spline order (2 for linear, 3 for quadratic, etc.)
         t:
            knot vector
         x (optional):
            an m-dimensional vector of values where the basis function is to be
            evaluated
        
        Output arguments:
         B:
            a matrix of m rows and numel(t)-n columns
        """
        n = self.order
        t = self.knots
        k = n-1
        
        B = np.zeros((len(x),len(t) - n))
        
        for i in range(len(t) - n):
            for j in range(len(x)):
                B[j,i] = self.bspline_basis(x[j], k, i, t)
            
        return B      
        
    def fit(self, x_data, y_data):
        
        Bmat =  self.basis_matrix(x_data)
        
        #Solve least squares y = B * c
        self.coeffs = np.linalg.lstsq(Bmat, y_data, rcond=None)[0]
    
    def predict(self, x_pred, coeffs):
        
        Bmat =  self.basis_matrix(x_pred)
        
        y_pred = tf.matmul(Bmat, coeffs)
        
        return y_pred

In [56]:
from itertools import chain, combinations
from itertools import combinations_with_replacement as combinations_w_r
from math import comb

class DynamicsBasis():
    
    def __init__(self, degree, X):  
#         super().__init__(degree = degree)
        self.m_samples = X.shape[0]
        self.dim = X.shape[1]
        self.degree = degree
        self.n_basis = comb(self.dim + self.degree, self.degree)

        self.include_bias = True
        self.X = tf.constant(X, dtype = tf.float32)
        
    @property
    def multi_index(self):
        
        comb = combinations_w_r
        start = int(not self.include_bias)
        combinations = chain.from_iterable(comb(range(self.dim), i) for i in range(start, self.degree + 1))
                                   
        
        return tf.stack([tf.math.bincount(c, minlength=self.dim) for c in combinations], axis = 0)
                                    
    @property
    def basis_names(self, input_dims = None):
        
        powers = self.multi_index.numpy()
        if input_dims is None:
            input_dims = ['x%d' % i for i in range(powers.shape[1])]
        basis_names = []
        for row in powers:
            inds = np.where(row)[0]
            if len(inds):
                name = " ".join("%s^%d" % (input_dims[ind], exp)
                                if exp != 1 else input_dims[ind]
                                for ind, exp in zip(inds, row[inds]))
            else:
                name = "1"
            basis_names.append(name)
            
        return basis_names
    
    def phi_matrix(self, X = None):
        
        if X is None:
            X = self.X
        else:
            X = tf.constant(X, dtype = tf.float32)
            
        
        powers = self.multi_index
        
        Phi = tf.zeros((X.shape[0], self.n_basis), dtype=tf.float32)
        
        for basis in range(self.n_basis):
            Phi[:,basis] = tf.reduce_prod(tf.pow(X, powers[basis,:]))
            
        
        print(Phi)
                
        return Phi
        
    def psi_matrix(self, X, t):
        
        Dt = t[1] - t[0]
        
        T = tf.convert_to_tensor(Dt * np.tril(np.ones(self.m_samples)), dtype = tf.float32)
        
        self.phi_matrix = tf.convert_to_tensor(self.fit_transform(X), dtype = tf.float32)
                
        return tf.matmult(T, self.phi_matrix)
    

        
        

In [58]:
X = tf.random.uniform((10,2), dtype = tf.float32)
db = DynamicsBasis(2,X)


db.phi_matrix()



InvalidArgumentError: cannot compute Pow as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Pow]

In [15]:
class SRSplineIdentification():
    
    def __init__(self, X, t, poly_degree, spline_order):
        
        self.Y_data = X.flatten()
        self.t = t
        self.m_samples = X.shape[0]
        self.dim = X.shape[1]
        knots = np.concatenate([t[0]*np.ones(3), t, t[-1]*np.ones(3)])
        self.bspline = Bspline(spline_order, knots)#Initialize bspline object
        
        self.spline_matrix = tnp.kron(np.eye(self.dim), self.bspline.basis_matrix(t))
        self.t_half = 0.5 * (t[1:-1] + t[0:-2])
        self.spline_matrix_half = tnp.kron(tnp.eye(self.dim), self.bspline.basis_matrix(self.t_half))
        self.dyn_basis = DynamicsBasis(poly_degree, X)#Initialize dynamics basis object
        
        self.parameters = self.initialize_parameters()
        
        self.eps = 1e-4
        self.alpha = 1e-1
        self.lambd = 1e-3

        
    def initialize_parameters(self):
        
        self.xi = tf.constant(np.random.rand(self.dyn_basis.num_params, self.dim).flatten(), dtype = tf.float32)
        self.theta = tf.constant(np.random.rand(self.bspline.num_params, self.dim).flatten(), dtype = tf.float32)
        
        return tf.concat([self.xi, self.theta], axis = 0)
    
    def spline_predict(self, mode):
        
        if mode == 0:
            return tf.matmul(self.spline_matrix, self.theta)
        else:
            print(self.spline_matrix_half)
            return tf.matmul(self.spline_matrix_half, self.theta)
        
    def spline_residual(self):
        
        Y_pred = self.spline_predict(0)
                        
        return self.Y_data - Y_pred
        
    def dynamics_residual(self):
        
        Y_tilde = self.Y_data[1:-1]
        
        Y_pred = self.spline_predict(1)
        
        psi_mat = self.dyn_basis.psi_matrix(self.t_half, Y_pred)
        
        D_big = np.kron(np.eye(self.dim), psi_mat)
                
        return Y_tilde - tf.matmul(D_big,self.xi)
        
    def l1_residual(self):
        
        W = tf.linalg.diag(1 / tf.abs(self.xi) + self.eps * tf.ones(len(xi)))
        L = tf.sqrt(W);
        
        return  tf.matmul(L, self.xi)
    
    def residual_vec(self):
        
        return tf.concat([self.dynamics_residual(), tf.sqrt(self.alpha) * self.spline_residual(),
                          tf.sqrt(self.lambd) * self.l1_residual()], axis = 0)
        
    def loss(self):
        
        return 0.5 * tf.reduce_sum(tf.square(self.residual_vec()))
        
    def get_jacobian(self):
        
        with tf.GradientTape(persistent = True) as tape:
            
            tape.watch(self.parameters)
            
            res_vec = self.residual_vec()
            
        jac = tape.jacobian(res_vec, self.parameters)
        
        del tape
        
        return jac            
        
    def get_gradient(self):
        
        with tf.GradientTape(persistent = True) as tape:
            
            tape.watch(self.parameters)
            
            loss_value = self.loss()
            
        grad = tape.gradient(loss_value, self.parameters)
        
        del tape
        
        return grad
        
    def train_step(self):
        pass
    
    def train(self):
        pass
        


In [93]:
from itertools import chain, combinations
from itertools import combinations_with_replacement as combinations_w_r
from math import comb

X = tf.random.uniform((10,2), dtype = tf.float32)
t = tf.linspace(0,1,100)
degree = 3
dim = 2
n_basis = comb(dim+degree, degree)
include_bias = True

comb = combinations_w_r
start = int(not include_bias)
combinations = chain.from_iterable(comb(range(dim), i) for i in range(start, degree + 1))
mi = tf.cast(tf.stack([tf.math.bincount(c, minlength=dim) for c in combinations], axis = 0), dtype = tf.float32)

In [95]:
Phi = tf.constant(tf.zeros((X.shape[0], n_basis), dtype=tf.float32))
        
for basis in range(n_basis):
        repeat(mi[basis,:], repeats=[X.shape[0]], axis=0)

        tf.tensor_scatter_nd_update(Phi, [i,basis], [tf.reduce_prod(tf.pow(X[i,:], mi[basis,:]))])


InvalidArgumentError: Inner dimensions of output shape must match inner dimensions of updates shape. Output: [10,10] updates: [1] [Op:TensorScatterUpdate]

In [79]:
mi[1,:]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 0.], dtype=float32)>

In [81]:
X[0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.053596616>

In [97]:
a = tf.constant([[1,1],[1,1],[1,1]],dtype = tf.float32)

In [98]:
b = tf.constant([[1,2],[3,4],[5,6]],dtype = tf.float32)

In [102]:
tf.reduce_prod(b,axis = 1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2., 12., 30.], dtype=float32)>

In [113]:
MI = mi[0,:]
for i in range(10):
    MI = tf.concat([MI,mi[0,:]], axis = 1)

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

In [112]:
MI

<tf.Tensor: shape=(22,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.], dtype=float32)>